name= "share"
compatibility_date = "2023-10-30"
account_id= "50f1b20eaa3f4c0ee0864aa2fc194e3b"
main = "src/index.ts"
workers_dev = false

# 如果没使用自定义域名，将BASE_URL改为 worker 的默认路由
vars = { ENVIRONMENT = "production", BASE_URL = "https://share.sslsecuse.workers.dev" }

# 如果不使用自定义域名，将下面的代码注释掉
#route = { pattern = "worker-hidden-frost-917f.sslsecuse.workers.dev", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "3a16935f8a084de3b3fb8c93295dbf97" },
]

[site]
bucket = "./static/dist"


[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'pastes'
